# coding: utf-8
"""
Wraps and extends the pelican-quickstart tool to create directories for Sass
(CSS) and Javascript sources.
"""
import os.path
import shutil

import pkg_resources

import pelican
import pelican.tools.pelican_quickstart

import homefront.bootstrap
import homefront.settings


def main():
    pelican.tools.pelican_quickstart.main()
    pelican_qs_conf = pelican.tools.pelican_quickstart.CONF
    basedir = pelican_qs_conf['basedir']

    settings_filename = os.path.join(basedir, pelican.DEFAULT_CONFIG_NAME)

    try:
        # Add plugins to pelican settings
        with open(settings_filename, "a") as settings_file:
            settings_file.write(
                "\n\n# Plugins\n"
                "PLUGINS = ('homefront.pelican.bootstrap', )")
    except (homefront.Error, OSError) as error:
        print(f"Error: {error}")

    try:
        settings = pelican.read_settings(settings_filename)
        homefront.settings.update(settings)

        # Create some homefront directories in the destination
        for subdir in ("scss", "js"):
            os.makedirs(os.path.join(basedir, subdir), exist_ok=True)

        cachedir = homefront.settings.get_cache_dir(settings, basedir)
        os.makedirs(cachedir, exist_ok=True)
    except (homefront.Error, OSError) as error:
        print(f"Error: {error}")

    try:
        # Create the base scss file
        with open(os.path.join(basedir, "scss/styles.scss"), "wb") as scss:
            content = pkg_resources.resource_string("homefront",
                                                    "resources/styles.scss")
            scss.write(content)

        with open(os.path.join(basedir, "scss/_theme.scss"), "w") as scss:
            scss.write("// Generated by homefront, put your styles here")
    except (homefront.Error, OSError) as error:
        print(f"Error: {error}")

    try:
        version = settings["BOOTSTRAP_VERSION"]
        bootstrap_dir = os.path.join(cachedir, f"bootstrap-{version}")
        homefront.bootstrap.download_bootstrap(version, bootstrap_dir)

        for filename in ("_variables.scss", ):
            shutil.copy(
                os.path.join(bootstrap_dir, "scss", "bootstrap", filename),
                os.path.join(basedir, "scss", filename))
    except (homefront.Error, OSError) as error:
        print(f"Error: {error}")

    try:
        # Add a .gitignore
        with open(os.path.join(basedir, ".gitignore"), "a") as gitignore:
            gitignore.write(
                "\n# Added by homefront\n"
                "__pycache__\n"
            )

            for ignored in ("CACHE_PATH", "OUTPUT_PATH", ):
                ignored = settings[ignored].rstrip(os.path.sep) + os.path.sep
                gitignore.write(f"{ignored}\n")
    except (homefront.Error, OSError) as error:
        print(f"Error: {error}")
